version: '3'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.35
    ports:
      - '16686:16686' # Query / UI
      - '14250:14250' # Jaeger Collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4317:4317' # gRPC receiver
    depends_on:
      - jaeger-all-in-one
